#!/usr/bin/env ruby

require 'net/http'
require 'nokogiri'

##### Argument parsing

if ARGV[0] == '--help' or ARGV.size != 1
  abort "Usage: #$0 <BGG username>"
end
USER = ARGV[0]

##### Main program

GEEKLIST_URL = URI.escape(
                 "https://boardgamegeek.com/geeklist/lists/user/#{USER}"
               )

uri = URI(GEEKLIST_URL)
Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
  games = []

  geeklists = Nokogiri::HTML(http.get(uri.request_uri).body)\
                            .css('td.mf/a')\
                            .collect { |a| a['href'].split('/')[2].to_i }
  geeklists.each do |geeklist|
    Nokogiri::XML(http.get("/xmlapi/geeklist/#{geeklist}").body)\
                 .css('/geeklist/item').each do |item|
      games << item['objectid']
    end
  end

  print http.get("/xmlapi/boardgame/#{games.join(',')}?stats=1").body
end
