#!/usr/bin/env ruby
# frozen_string_literal: true

require 'nokogiri'

##### Argument parsing

if ARGV[0] == '--help' || ARGV.size != 1
  abort "Usage: #{$PROGRAM_NAME} <category>"
end
CATEGORY = ARGV[0]

##### Main program

boardgames = Nokogiri::XML($stdin.read)
boardgames.search('//boardgames/boardgame').each do |boardgame|
  unless boardgame.search('./boardgamecategory')
                  .detect { |category| category.text == CATEGORY }
    boardgame.remove
  end
end
print boardgames
